name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Dar permisos gradlew
        run: chmod +x gradlew

      - name: Build proyecto
        run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Dar permisos gradlew
        run: chmod +x gradlew

      - name: Ejecutar tests
        run: ./gradlew test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploy EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo yum update -y
            sudo yum install docker git -y
            sudo service docker start
            sudo usermod -aG docker ec2-user

            cd /home/ec2-user

            if [ ! -d "GRUPO_5_DEVOPS" ]; then
              git clone https://github.com/Wally20068/GRUPO_5_DEVOPS.git
            fi

            cd GRUPO_5_DEVOPS/user-service-ci-cd-master

            docker compose down
            docker compose up --build -d