name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Dar permisos gradlew
        run: chmod +x gradlew

      - name: Build proyecto
        run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Dar permisos gradlew
        run: chmod +x gradlew

      - name: Ejecutar tests
        run: ./gradlew test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploy placeholder
        run: echo "Deploy hacia EC2 pendiente"